// Generated by CoffeeScript 1.6.3
var adjectives, animals, getArrayElFromInt, hash, md5, upperFirst;

md5 = require('./md5').md5;

animals = require('./animals').long;

adjectives = require('./adjectives');

console.log(md5);

upperFirst = function(str) {
  if (str === '') {
    return str;
  }
  return str.charAt(0).toUpperCase() + str.slice(1);
};

getArrayElFromInt = function(arr, int, intmax, intmin) {
  var index, ratio;
  if (intmax == null) {
    intmax = Math.pow(2, 32);
  }
  if (intmin == null) {
    intmin = 0;
  }
  ratio = int / (intmax - intmin);
  index = Math.floor(ratio * arr.length);
  return arr[index];
};

hash = function(input) {
  var adjective, adjectivesHashInt, animal, animalsHashInt, inputHash, out;
  inputHash = md5(input);
  animalsHashInt = parseInt(inputHash.substr(0, 8), 16);
  adjectivesHashInt = parseInt(inputHash.substr(8, 8), 16);
  animal = getArrayElFromInt(animals, animalsHashInt);
  adjective = getArrayElFromInt(adjectives, adjectivesHashInt);
  return out = upperFirst(adjective) + " " + upperFirst(animal);
};

module.exports = hash;
