// Generated by CoffeeScript 1.6.3
var adjectives, animals, hash, nodeHash, upperFirst;

nodeHash = require('node_hash');

animals = require('./animals').long;

adjectives = require('./adjectives');

upperFirst = function(str) {
  if (str === '') {
    return str;
  }
  return str.charAt(0).toUpperCase() + str.slice(1);
};

hash = function(input) {
  var adjective, adjectiveHashInt, animal, animalHashInt, inputHash, out;
  inputHash = nodeHash.md5(input);
  animalHashInt = parseInt(inputHash.substr(0, 8), 16);
  adjectiveHashInt = parseInt(inputHash.substr(8, 8), 16);
  animal = animals[animalHashInt % animals.length];
  adjective = adjectives[adjectiveHashInt % adjectives.length];
  return out = upperFirst(adjective) + " " + upperFirst(animal);
};

module.exports = hash;
