// Generated by CoffeeScript 1.6.3
var adjectives, animals, getArrayElFromInt, hash, hashStr, md5, random, randomEl, randomInt, randomStr, upperFirst;

md5 = require('./md5').md5;

animals = require('./animals').long;

adjectives = require('./adjectives');

upperFirst = function(str) {
  if (str === '') {
    return str;
  }
  return str.charAt(0).toUpperCase() + str.slice(1);
};

getArrayElFromInt = function(arr, int, intmax, intmin) {
  var index, ratio;
  if (intmax == null) {
    intmax = Math.pow(2, 32);
  }
  if (intmin == null) {
    intmin = 0;
  }
  ratio = int / (intmax - intmin);
  index = Math.floor(ratio * arr.length);
  return arr[index];
};

randomEl = function(arr) {
  return arr[randomInt(0, arr.length - 1)];
};

randomInt = function(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
};

hash = function(input, salt) {
  var adjective, adjectivesHashInt, animal, animalsHashInt, inputHash;
  if (salt == null) {
    salt = "";
  }
  inputHash = md5(salt + input);
  animalsHashInt = parseInt(inputHash.substr(0, 8), 16);
  adjectivesHashInt = parseInt(inputHash.substr(8, 8), 16);
  animal = getArrayElFromInt(animals, animalsHashInt);
  adjective = getArrayElFromInt(adjectives, adjectivesHashInt);
  return [upperFirst(adjective), upperFirst(animal)];
};

random = function(input) {
  var adjective, animal;
  adjective = randomEl(adjectives);
  animal = randomEl(animals);
  return [upperFirst(adjective), upperFirst(animal)];
};

hashStr = function(input) {
  return hash(input).join(' ');
};

randomStr = function(input) {
  return random(input).join(' ');
};

module.exports = {
  adjectives: adjectives,
  animals: animals,
  hash: hash,
  hashStr: hashStr,
  random: random,
  randomStr: randomStr
};
